# tirgul 6
# a good source to study dictionary:
# https://www.programiz.com/python-programming/dictionary-comprehension


# 1. zip function (named after physical zip, just like in jeans)
s1 = [2, 3, 1]
s2 = ['b', 'a', 'c']
zipRes = zip(s1, s2)
print(type(zipRes))
result = list(zip(s1, s2))
print(result)
print(type(zipRes))
print(zipRes)
print("Meaning we should convert to list in order to properly view zip object")


# 2 self excercise: 3 way zipping
# # from the following lists
# s1 = [2, 3, 1]
# s2 = ['b', 'a', 'c']
# s3 = ['s31', 's32', 's33']
# # 3.1. Generate the list: [(2, 'b', 's31'), (3, 'a', 's32'), (1, 'c', 's33')]















# solution:
# result = list(zip(s1, s2, s3))
# print(result)

# # 3.2 self excercise: From the generated list print the 's32' item




# solution:
# print(result[1][2])

# 3. dictionary: has items with keys and values
# thisdict = {
#     "brand": "Ford",
#     "model": "Mustang",
#     "year": 1964
# }
# print(thisdict)
# thisdict["year"] = 2018
# print(thisdict)


# # 4. dictionary can be generated by lists
# # dictionary has items with keys and values.
# keys = ['Ten', 'Twenty', 'Thirty']
# values = [10, 20, 30]
# sampleDict = dict(zip(keys, values))
# print(sampleDict)
# #


# # 5 add value to a dictionary
# thisdict["Wheels"] = "Michelin"
# print(thisdict)

# # 6 print all key names in dictionary:
# for key in thisdict:  # key is just a variable name
#     print(key)

# # 7 self excecise: Print all values in the dictionary, one by one:



# solution:
# for key in thisdict:
#     print(thisdict[key])

# # 8 the values in the dictionary can be accessed by the values() method
# for value in thisdict.values():
#     print(value)

# # 9 if we wish to get both keys and vlues we may use the items() method:
# for key, value in thisdict.items():
#     print(key, value)

# self excercise: print the length of dictionary



# solution:
# print(len(thisdict))


# # # 10. self excecise dictionary:
# ##merge 2 dictionaries into one.
# dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
# dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
#  #
#  #
# ##solution:
# dict3 = dict1.copy()
# dict3.update(dict2)
# print(dict3)
# # #

### 11. multiple values in dictionary
# word_freq = {'is': [1, 3, 4, 8, 10],
#             'at': [3, 10, 15, 7, 9],
#             'test': [5, 3, 7, 8, 1],
#             'this': [2, 3, 5, 6, 11],
#             'why': [10, 3, 9, 8, 12]}

# # print all values
# for key in word_freq:
#    print(word_freq[key])
##
### self excercise: print just the third values (i.e. 4,15,7,5,9)    

# solution:
##for key in word_freq:
##    print(word_freq[key][2])
    
# # self learning:
# Dictionary excercises with solutions can be found at: https://pynative.com/python-dictionary-exercise-with-solutions/

# 1 Given the dictionary:
# # ampleDict = {
#   "name": "Kelly",
#   "age":25,
#   "salary": 8000,
#   "city": "New york"

# }
# Print expected output:
# {'name': 'Kelly', 'salary': 8000}

# solution:
# # 1. sampleDict = {
#   "name": "Kelly",
#   "age":25,
#   "salary": 8000,
#   "city": "New york" }

# keys = ["name", "salary"]

# newDict = {k: sampleDict[k] for k in keys}
# print(newDict)

# 2. by deletion, given the dictionary:
# # sampleDict = {
#   "name": "Kelly",
#   "age":25,
#   "salary": 8000,
#   "city": "New york"

# }
# delete items to result into dictionary
# {'city': 'New york',
#  'age': 25}

# # solution:
# sampleDict = {
#   "name": "Kelly",
#   "age":25,
#   "salary": 8000,
#   "city": "New york"
# }
# keysToRemove = ["name", "salary"]

# sampleDict = {k: sampleDict[k] for k in sampleDict.keys() - keysToRemove}
# print(sampleDict)



